version: "3.4"
services:
  frontend:
    container_name: frontend
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend/:/usr/src/frontend
    entrypoint: /bin/sh
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
  backend:
    container_name: backend
    image: strapi/strapi
    volumes:
      - ./backend:/srv/app
    ports:
      - '1337:1337'
