version: "3.4"
services:
  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: Dockerfile-Nuxt
    volumes:
      - ./frontend/:/usr/src/frontend
    entrypoint: /bin/sh
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile-Strapi
    volumes:
      - ./backend:/srv/app/strapi
    ports:
      - '1337:1337'