version: "3.4"
services:
  nuxt:
    container_name: nuxt
    build:
      context: ./
      dockerfile: nuxt.dockerfile
    volumes:
    #  - ./nuxt/:/usr/src/nuxt
       - ./strapi/public/uploads/:/usr/src/nuxt/static/
    ports:
      - '3000:3000'
    environment:
      - STRAPI_URL=strapi
      - CHOKIDAR_USEPOLLING=true
    tty: true
    networks:
      - app
  strapi:
    container_name: strapi
    build:
      context: .
      dockerfile: strapi.dockerfile
    volumes:
      - ./strapi:/opt/app
    ports:
      - '1337:1337'
    networks:
      - app
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch
    volumes:
      - ./meilisearch:/data.ms
    ports:
      - '7700:7700'
    env_file:
      - ./meilisearch/meilisearch.env
    networks:
      - app
  nginx:
    container_name: nginx
    image: nginx:1.21.6-alpine
    ports:
      - "80:80"
    expose:
      - 80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - app
    links: 
      - nuxt
  publish:
    container_name: strapi_events
    image: ghcr.io/badsyntax/strapi-webhook-actions-proxy:latest
    ports:
      - '5000:5000'
    env_file:
      - 'strapi_publish.env'
    networks:
      - app
networks:
  app:
    driver: bridge