version: "3.4"
services:
  nuxt:
    container_name: nuxt
    build:
      context: ./
      dockerfile: nuxt.dockerfile
    volumes:
      - ./nuxt/:/usr/src/nuxt
    entrypoint: /bin/sh
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
  strapi:
    container_name: strapi
    build:
      context: .
      dockerfile: strapi.dockerfile
    volumes:
      - ./strapi:/opt/app
    ports:
      - '1337:1337'
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch
    volumes:
      - ./meilisearch:/data.ms
    ports:
      - '7700:7700'