name: Redeploy app on code change
on: 
  push:
    branches: [ trunk ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password ${{ secrets.SSHKEY }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        command_timeout: 200m
        script: |
          # Navigate to project folder
          cd ../var/www/ismerdmeg
          # Stop project
          sh stop.sh
          # Pull Changes
          git pull
          # Start project
          sh start-prod.sh