name: CI

# 1
# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ trunk ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true
#2
env:
  REGISTRY: "registry.digitalocean.com"
  IMAGE_NAME: "ismerdmeg"

#3
jobs:   
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          #passphrase: ${{ secrets.PASSPHRASE }}
          envs: IMAGE_NAME,REGISTRY,{{ secrets.DIGITALOCEAN_ACCESS_TOKEN }},GITHUB_SHA
          script: |
            # Navigate to project folder
            cd ../var/www/ismerdmeg
            # Stop project
            sh stop.sh
            # Navigate outside the project folder
            cd ..
            # Delete old project
            sudo rm -rf ismerdmeg
            # Remove old containers
            docker system prune --force --all
            # Clone project
            git clone https://github.com/vertesip/ismerdmeg.git
            # Navigate into new project
            cd ismerdmeg
            # Build new project
            sh start.sh
