name: remote ssh command
on: 
  push:
    branches: [ trunk ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        # port: ${{ secrets.PORT }}
        script: |
          # Navigate to project folder
          cd ../var/www/ismerdmeg
          # Stop project
          sh stop.sh
          # Navigate outside the project folder
          cd ..
          # Delete old project
          sudo rm -rf ismerdmeg
          # Remove old containers
          docker system prune --force --all
          # Clone project
          git clone https://github.com/vertesip/ismerdmeg.git
          # Navigate into new project
          cd ismerdmeg
          # Build new project
          sh start.sh
