name: Redeploy app on code change
on: 
  push:
    branches: [ trunk ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        command: |
          # Navigate to project folder
          cd ../var/www/ismerdmeg
          # Stop project
          sh stop.sh
          # Pull Changes
          git pull
          # Start project
          sh start-prod.sh