name: Rebuild frontend on Strapi content change
on:
  repository_dispatch:
    types: [strapi_updated]
jobs:

  build:
      name: Build
      runs-on: ubuntu-latest
      steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          command_timeout: 200m
          script: |
            # Navigate to project folder
            cd ../var/www/ismerdmeg
            docker exec --tty nuxt /bin/sh
            while ! npm run build && fuser -k 3000/tcp; do sleep 1; done
            docker compose restart nuxt
            